name: Release a CV

on:
    push:
        tags:
            - "*"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: "*_CV.pdf"
                  make_latest: true
